var mongoose = require ('mongoose');
var validator = require('validator');

var requiredString =
  {
    'type': 'String',
    'required': 'true'
  };
var oCity = {
        _id: String,//autogenerated bt our server
        c: String,
        s: String,
        p: Number,
        d: String,
        sf : String,
        address_components:{
              street_number: String,//'short_name'
              route: String,//'long_name'
              sublocality_level_2: String,//'long_name'
              sublocality_level_3: String,//'long_name'
              sublocality_level_1: String,//'long_name'
              sublocality: String,//'long_name'
              locality: String,//'long_name'
              administrative_area_level_2: String,//'long_name'
              administrative_area_level_1: String,//'short_name',
              administrative_area_level_1_f: String,//'long_name'
              country : String,//'short_name',
              country_f : String,//'long_name',
              postal_code: Number,//'short_name'
        },
        formatted_address : String,
        geometry : {
            location:{
                lat: Number,
                lng:Number
            }
        },
        place_id:String,
        types:[String],
        url : String,
        vicinity:String     
    };
var tradeSchema = new mongoose.Schema(
  {
 
    'source':oCity,
      'destination':oCity,
      'amount' :
    {
      'type':Number,
      'required':true
    },
    'weight':
          {
            'type': Number,
            'min': 0
            
          },
    'date':{
      'from': {
        'type': Date
      },
      'to': {
        'type': Date
      }
    },
    'truckType':
    {
        '_id' : String,
        'code': String,
        'truck_type': String
    },
    'rate' : {
      'type': 'String',
      'enum': ['RS','USD','EURO'],
       default : 'RS'
    },
    'ratePostId' : String,
    'ratePostDate' : String,
    'userId':
    {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User'
    },
    'created_at': {'type': Date, default: new Date()},
    'latModified': {'type': Date, default: new Date()}
    
  }
 );

module.exports = mongoose.model('trades', tradeSchema);
