var mongoose = require ('mongoose');
var validator = require('validator');

var requiredString =
	{
		type: String,
		required: true
	};
var oCity = {
		_id: String,//autogenerated bt our server
		c: String,
		s: String,
		p: Number,
		d: String,
		sf : String,
		address_components:{
			  street_number: String,//'short_name'
			  route: String,//'long_name'
			  sublocality_level_2: String,//'long_name'
			  sublocality_level_3: String,//'long_name'
			  sublocality_level_1: String,//'long_name'
			  sublocality: String,//'long_name'
			  locality: String,//'long_name'
			  administrative_area_level_2: String,//'long_name'
			  administrative_area_level_1: String,//'short_name',
			  administrative_area_level_1_f: String,//'long_name'
			  country : String,//'short_name',
			  country_f : String,//'long_name',
			  postal_code: Number,//'short_name'
		},
		formatted_address : String,
		geometry : {
			location:{
				lat: Number,
				lng:Number
			}
		},
		place_id:String,
		types:[String],
		url : String,
		vicinity:String		
	 };
var intNumber =
	{
		'type': 'Number',
		'set' :
			function(num) {
				return Math.abs(Math.round(num));
			}
	};

var PartLoadUserSchema = new mongoose.Schema(
{
	USERID:String,
	owner_name : String,
	company_name: String,
	mobile: 
	{
		type: Number,
		required: true,
		unique: true,
		dropDups: true,
		set :
				function(num) {
					return Math.abs(Math.round(num));
				}
	},
	type :
	{
		type: String,
		enum: ['broker','truck_owner','customer', 'aggregator', 'transporter','pnm','sl','cha','partLoad'],
		default : 'partLoad'
	},
	email :
	{
		type: String,
		set :
			function(email) {
				return email.toLowerCase();
			},
		validate: [validator.isEmail, "Invalid Email"]
	},
	password: requiredString,
	pwd: String,
	otp:intNumber,
	nOtp:intNumber,
	tnc_accepted :{
			type: Boolean,
			default: false
	},
	role :{
			type: String,
			enum: ['user','showAdmin', 'updateAdmin', 'superAdmin','dealer'],
			 default : 'user'
	},
	status :{
			type: String,
			enum: ['inactive', 'active', 'blocked'],
			default: 'inactive'
	},
	short_description: String,
	landline : {
			code:intNumber,
			number:intNumber
	},
	city : oCity,
	office_address : String,
	'noncust_details' :{
		pickUpArea:[{area:oCity,pincode:intNumber}],
		branch_cities:[{city:oCity,pincode:intNumber}],
		daily_serv_cities:[{city:oCity,pincode:intNumber}]
	},
	modes_of_transportation:[{type:String}],
	services:[{type:String}],
	created_at: {type: Date, default: new Date()},
	latModified: {type: Date, default: new Date()}
});

module.exports = mongoose.model('PartloadUser', PartLoadUserSchema);